// utils/mockPhotos.ts
import { Photo } from '../types';

export const mockPhotos: Photo[] = [
    {
        id: '0',
        url: '/properties/after/after1.jpg',
        property: 'Cozy Cottage',
        style: 'Modern',
        date: '2024-02-10',
        location: '123 Main St, Anytown, AT 12345',
        description: 'Living room after virtual staging with modern furniture and decor.',
        tags: ['modern', 'living room', 'cozy'],
        roomType: 'Living Room',
        dimensions: '20x15 ft',
        beforeImage: '/properties/before/before1.jpg',
        afterImage: '/properties/after/after1.jpg',
        project: 'Cozy Cottage Staging',
        status: 'published',
        designer: 'Alex Johnson',
        clientFeedback: 'Loved the modern look!',
        resolution: '1920x1080',
        fileSize: '2.5MB',
        uploadedBy: 'user123',
        uploadDate: new Date('2024-02-10'),
        lastModified: new Date('2024-02-12'),
    },
    {
        id: '1',
        url: '/properties/after/after2.jpg',
        property: 'Cozy Cottage',
        style: 'Modern',
        date: '2024-02-10',
        location: '123 Main St, Anytown, AT 12345',
        description: 'Living room after virtual staging with modern furniture and decor.',
        tags: ['modern', 'living room', 'cozy'],
        roomType: 'Living Room',
        dimensions: '20x15 ft',
        beforeImage: '/properties/before/before1.jpg',
        afterImage: '/properties/after/after2.jpg',
        project: 'Cozy Cottage Staging',
        status: 'published',
        designer: 'Alex Johnson',
        clientFeedback: 'Loved the modern look!',
        resolution: '1920x1080',
        fileSize: '2.5MB',
        uploadedBy: 'user123',
        uploadDate: new Date('2024-02-10'),
        lastModified: new Date('2024-02-12'),
    },
    {
        id: '2',
        url: '/properties/after/after3.jpg',
        property: 'Cozy Cottage',
        style: 'Modern',
        date: '2024-02-10',
        location: '123 Main St, Anytown, AT 12345',
        description: 'Living room after virtual staging with modern furniture and decor.',
        tags: ['modern', 'living room', 'cozy'],
        roomType: 'Living Room',
        dimensions: '20x15 ft',
        beforeImage: '/properties/before/before1.jpg',
        afterImage: '/properties/after/after3.jpg',
        project: 'Cozy Cottage Staging',
        status: 'published',
        designer: 'Alex Johnson',
        clientFeedback: 'Loved the modern look!',
        resolution: '1920x1080',
        fileSize: '2.5MB',
        uploadedBy: 'user123',
        uploadDate: new Date('2024-02-10'),
        lastModified: new Date('2024-02-12'),
    },
    {
        id: '3',
        url: '/properties/before/before1.jpg',
        property: 'Cozy Cottage',
        style: 'Modern',
        date: '2024-02-10',
        location: '123 Main St, Anytown, AT 12345',
        description: 'Living room after virtual staging with modern furniture and decor.',
        tags: ['modern', 'living room', 'cozy'],
        roomType: 'Living Room',
        dimensions: '20x15 ft',
        beforeImage: '/properties/before/before1.jpg',
        afterImage: '/properties/after/after3.jpg',
        project: 'Cozy Cottage Staging',
        status: 'published',
        designer: 'Alex Johnson',
        clientFeedback: 'Loved the modern look!',
        resolution: '1920x1080',
        fileSize: '2.5MB',
        uploadedBy: 'user123',
        uploadDate: new Date('2024-02-10'),
        lastModified: new Date('2024-02-12'),
    },
];
